// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Data.Context;

namespace Shared.Data.Migrations
{
    [DbContext(typeof(SuperContext))]
    [Migration("20190520225418_AddView_Statuses")]
    partial class AddView_Statuses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Shared")
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shared.Domain.Local.Language", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Code")
                        .HasColumnType("char(2)");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Shared.Domain.Local.StatusTitle", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("LanguageId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("StatusTitles");
                });

            modelBuilder.Entity("Shared.Domain.Local.StatusValue", b =>
                {
                    b.Property<int>("Id");

                    b.Property<bool>("IsDefault");

                    b.HasKey("Id");

                    b.ToTable("StatusValues");
                });

            modelBuilder.Entity("Shared.Domain.Local.StatusTitle", b =>
                {
                    b.HasOne("Shared.Domain.Local.StatusValue", "StatusValue")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Local.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
