// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Serita.Data.Context;

namespace Serita.Data.Migrations
{
    [DbContext(typeof(SuperContext))]
    [Migration("20190520225720_AddView_LanguagesRefShared")]
    partial class AddView_LanguagesRefShared
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Serita")
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Serita.Domain.Local.MenuItemTitle", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id", "LanguageId");

                    b.ToTable("MenuItemTitles");
                });

            modelBuilder.Entity("Serita.Domain.Local.MenuItemValue", b =>
                {
                    b.Property<int>("Id");

                    b.Property<bool>("HasSeparator");

                    b.Property<string>("IconName")
                        .HasMaxLength(32);

                    b.Property<bool>("IsChecked");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Link")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64);

                    b.Property<byte>("Ordering");

                    b.Property<int?>("ParentId");

                    b.Property<string>("ShortCut")
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItemValues");
                });

            modelBuilder.Entity("Serita.Domain.Local.MenuItemTitle", b =>
                {
                    b.HasOne("Serita.Domain.Local.MenuItemValue", "MenuItemValue")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Serita.Domain.Local.MenuItemValue", b =>
                {
                    b.HasOne("Serita.Domain.Local.MenuItemValue", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
